### PR TITLE
Upgrade to Selenium 2.52.0

### PR DESCRIPTION
**Pull request by davehunt**
@stephendonner r?

### CODE REVIEW

**Comment by davehunt** [comment]
I've also included adding Firefox 43 & 44 to this patch. The changes were tested independently.

**Comment by stephendonner** [comment]
Sorry for the (continued) delay on this; would great if @mozilla/web-qa-sorcerers could also take a look, in my sluggishness.  I'm having issues setting up the environment on my Windows desktop at work; will try my VM tomorrow, instead.

**Comment by davehunt** [comment]
I'm happy for the review to be just based on the changes and to not include any testing. I've already tested this on staging, and am confident that there are no major issues with the new versions. Firefox 45 will be released today, and then we'll be three versions behind release.

**Comment by stephendonner** [comment]
r+; since I'm still Buildmaster, I know the failures seen in the grid.sanity job (http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/grid.sanity/26/) are also experienced in the production Jenkins; they are:

1. proxy timeouts
2. AMO-review timestamp differences between UTC + PDT/PST (https://github.com/mozilla/Addon-Tests/issues/821)
3. Socorro stage - https://bugzilla.mozilla.org/show_bug.cgi?id=1255209
4. Marketplace failures are due to including DevHub in the run, which is expected to, currently, and will continue failing on dev/stage, until address it separately.

**Comment by davehunt** [comment]
Thanks @stephendonner. I'll hold off rolling this out to production in case you want to work together on this.

**Pull request merged**
